---
title: "Multiple Linear Regression"
author: "Jason Bryer"
date: 2021-04-21
draft: false
categories: ["R", "Meetups", "Announcements"]
tags: ["Annoucement"]
#summary: Recording and slides from the class meetup.
---

[Click here](/slides/09-Multiple_Regression.html#1) to open the slides.

<iframe width="560" height="315" src="https://www.youtube.com/embed/e27sxMFHzKM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<!--more-->

[Click here](/slides/09-Multiple_Regression.html#1) to open the slides.

[Shiny app to visualize interactions, simple main effects, simple slopes and model surfaces in 2-IV linear models](https://shiny.rit.albany.edu/stat/mod2/)

<iframe width="560" height="315" src="https://www.youtube.com/embed/e27sxMFHzKM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Here is the R script for analyzing the tutorial dataset:

```{r, eval=TRUE, message=FALSE, warning=FALSE}
library(openintro)
library(ggplot2)

data("tourism", package = 'openintro') # Question 8.21

ggplot(tourism, aes(x = visitor_count_tho)) +
	geom_histogram()

ggplot(tourism, aes(x = tourist_spending)) +
	geom_histogram()

ggplot(tourism, aes(x = visitor_count_tho, y = tourist_spending)) +
	geom_point() +
	geom_smooth(method = 'lm', se = FALSE, formula = y ~ x) +
	scale_x_log10() + scale_y_log10()

lm.out <- lm(visitor_count_tho ~ tourist_spending, data = tourism)
summary(lm.out)

lm.out.log <- lm(log(visitor_count_tho) ~ log(tourist_spending), data = tourism)
summary(lm.out.log)

tourism$residual <- resid(lm.out)
tourism$residual.log <- resid(lm.out.log)

ggplot(tourism, aes(x = tourist_spending, y = residual)) +
	geom_hline(yintercept = 0) +
	geom_point()

ggplot(tourism, aes(x = tourist_spending, y = residual.log)) +
	geom_hline(yintercept = 0) +
	geom_point()

hist(tourism$residual)
ggplot(tourism, aes(x = residual)) + geom_histogram(bins = 7)

ggplot(tourism, aes(x = residual)) + geom_density()
```


### Here is the R script that looks at how the F-statistic is calculated.

```{r, eval=TRUE, message=FALSE, warning=FALSE}
poverty <- read.table("https://raw.githubusercontent.com/jbryer/DATA606Spring2021/master/course_data/poverty.txt", h = T, sep = "\t")
names(poverty) <- c("state", "metro_res", "white", "hs_grad", "poverty", "female_house")
poverty <- poverty[,c(1,5,2,3,4,6)]
head(poverty)

# Sample size
n <- nrow(poverty)
# Total variance for the outcome variable
SSy <- sum((poverty$poverty - mean(poverty$poverty))^2)

# Start with one predictor
lm.out1 <- lm(poverty ~ female_house, data = poverty)
summary(lm.out1)
anova(lm.out1)
# Note that F-statistic is the same summary(lm.out1).
# From the ANOVA output, it is the ratio of mean square model
# (i.e. female_house here) to mean square error/residual.
132.568 / 7.095

# However, this only works with one predictor.
SSresid <- sum(lm.out1$residuals^2)
SSmodel <- SSy - SSresid
k <- length(lm.out1$coefficients) - 1
((SSmodel) / k) / (SSresid / (n - (k + 1)))

lm.out2 <- lm(poverty ~ female_house + white, data = poverty)
summary(lm.out2)
anova(lm.out2)

# How is the F-Statistic calculated
# Ho: All coefficients are zero
# Ha: At least one coefficient is nonzero
n <- nrow(poverty)
SSresid <- sum(lm.out2$residuals^2)
SSy <- sum((poverty$poverty - mean(poverty$poverty))^2)
SSmodel <- SSy - SSresid
k <- length(lm.out2$coefficients) - 1
((SSmodel) / k) / (SSresid / (n - (k + 1)))
```
